---
- hosts: Application
  tasks:
  - name: Install Apache
    yum: 
      name: httpd
      state: installed
    become: yes 
    tags:
      - install    
  - name: copy the index.html file
    copy:
      src: index.html
      dest: /var/www/html/
    become: yes
    tags:
      - copy    
  - name: Starting Apache
    service:
      name: httpd
      state: started 
    become: yes
    tags:
      - start
  - name: stop the Apache
    service:
      name: httpd
      state: stopped
    become: yes
    tags:
      - stop    
  - name: uninstall Apache
    yum:
      name: httpd
      state: absent
    become: yes
    tags:
      - uninstall
