---
- hosts: myappservers
  tasks: 
  - name: install apache
    yum: 
      name: httpd
      state: latest      
    become: true
    tags:
      - install
  - name: start Apache
    service:
      name: httpd
      state: started
    become: true  
    tags:
      - start
  - name: copy html file
    copy:
      src: index.html
      dest: /var/www/html/
    become: true
    tags:
      - copy
